### ISSUE TITLE
Documentation for issuing attestation through smart contract

### ISSUE THREAD

**Issue by divine-comedian** [EthSign/ethglobal-bangkok-2024-tracker#1]
### Description

Is there any documentation for creating an attestation in solidity through a smart contract function?

**Comment by raa-dev** [comment]
does this helps? https://docs.sign.global/for-builders/index-1/index/index
@divine-comedian

**Comment by boyuanx** [comment]
https://github.com/EthSign/sign-protocol-examples/blob/main/src/01-actually-met-irl/ActuallyMetIRL.sol
