### ISSUE TITLE
[GENERAL] - "Error: Field length is not equal" issue

### ISSUE THREAD

**Issue by raa-dev** [EthSign/ethglobal-bangkok-2024-tracker#2]
### Description

I'm using your SDK through ts, but I have an issue during the client's createAttestation calling process. It says "Error: Field length is not equal", but I verified the data I'm submitting follows the schema I created.

schema:
```typescript
export const schema: SchemaItem[] = [
    {
        name: "field1", type: "string"
    },
    {
        name: "field2", type: "string"
    },
    // ...
    {
        name: "field N", type: "string"
    }
]
```
payload formatting and calling client's fn

```typescript
// ...
        const payload = {
            field1: formData.get("field1"),
            field2: formData.get("field2"),
            //...
            fieldN: formData.get("fieldN")
            }
        const res = await attestSchema(
            schemaId,
            JSON.stringify(payload),
            fieldN
        );

export const attestSchema = async (
    schemaId: string,
    contractDetails: string,
    signer: string
) => {
    const res = await client.createAttestation({
        schemaId: schemaId,
        data: {
            contractDetails,
            signer
        },
        indexingValue: signer.toLowerCase()
    });
    return res;
}
```

### Screenshots
<img width="359" alt="Screenshot 2024-11-16 at 12 22 14 p m" src="https://github.com/user-attachments/assets/8068f692-ad28-4f5b-b487-d6281fc7f276">

**Comment by jbettenc** [comment]
The example you were following for the notary (where it has the `contractDetails` and `signer`) corresponds to a schema that has two entries in its data field: `contractDetails` is a string, and `signer` is also a string. It is important to note that this is the attestation body.

In your example, I am assuming that your `payload` is intended to be the attestation body (or the attestation's data). In this case, you would do something like the following:
```
// Note that this must match your schema. For example, if your schema expects exactly N items, then your payload will have N items
const payload = {
    field1: formData.get("field1"),
    field2: formData.get("field2"),
     //...
    fieldN: formData.get("fieldN")
}
const res = await attestSchema(
    schemaId,
    payload
);

export const attestSchema = async (
    schemaId: string,
    payload: Object, // You could be more specific here to your schema's requirement
) => {
    const res = await client.createAttestation({
        schemaId: schemaId,
        data: payload,
        indexingValue: signer.toLowerCase() // This assumes your signer is defined somewhere
    });
    return res;
}
```

**Comment by jbettenc** [comment]
Closing this issue as it seems to have solved your problem. Please feel free to re-open or create a new issue if something else comes up.
