### ISSUE TITLE
[GENERAL] - Reputation between employee and employer

### ISSUE THREAD

**Issue by ghost** [EthSign/ethglobal-bangkok-2024-tracker#5]
### Description

We are building a Tinder style app between employee and employers that is based on Sign protocol reputation mechanism.

Each match, task completion, work history, rating is done via Sign protocol attestation and we use this history to build the profile scoring.

Should we use a general schema for all use cases above or there should be separate schema for each?

Thanks.

https://ethglobal.com/showcase/trustme-god3u

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by jbettenc** [comment]
Your screenshot did not come through, but my expectation is that you should try to generalize everything into a single schema. You could possibly store an entry type and the relevant information for that entry. However, this all comes down to what you are trying to achieve. There may not be ways to generalize different types of entries at all - in this case, you may need to create separate schemas.
